platform :ios, "7.0"

target :App, :exclusive => true do
	pod 'Objection', '~> 1.6'
	pod 'libextobjc', '~> 0.3'

	link_with "MSSpec"

	target :Tests do
		pod 'Kiwi', '~> 2.3.0'

		link_with "MSSpecTests"
	end
end
